services:
  db:
    image: postgres:12
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: trupwd
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

# Run container:
#  docker-compose up -d
#
# Connect to postgres:
#  docker exec -it postgres-db psql -U postgres
